[package]
name = "inventory-rs"
version = "0.1.0"
edition = "2021"
description = "An inventory system independant of item data."
license = "GPL-2.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
